---
name: vsg
description: VHDL Style Guide (VSG), coding style enforcement for VHDL
homepage: https://github.com/jeremiah-c-leary/vhdl-style-guide
licenses:
  - GPL-3.0
languages:
  - VHDL
categories:
  - Formatter

source:
  id: pkg:pypi/vsg@3.25.0

bin:
  vsg: pypi:vsg
